#! /bin/bash
echo "_______________S T A R T    S Y S T E M   G E N E R A T I O N___________________"
echo
make
echo
echo "_______________F I N I S H    S Y S T E M   G E N E R A T I O N___________________"
