# encoding: UTF-8

RM := rm -rf

CC := gcc
CC_FLAGS := -O2 -Wall -std=c99
CC_FLAGS += $(GLOBAL_CC_FLAGS)

ABSLOAD_BIN := bin/absload

ABSLOAD_SRC_DIR := src
ABSLOAD_OBJ_DIR := obj

# ABSLOAD INCLUDES
ABSLOAD_INCLUDES := $(PL1_UTILS_DIR)/src
ABSLOAD_INCLUDES := $(addprefix -I, $(ABSLOAD_INCLUDES))

# ABSLOAD DEFINITIONS
# ABSLOAD_DEFINITIONS :=
# ABSLOAD_DEFINITIONS +=

# ABSLOAD LIBS DIR
ABSLOAD_LIB_DIRS := $(PL1_UTILS_DIR)
ABSLOAD_LIB_DIRS := $(addprefix -L, $(ABSLOAD_LIB_DIRS))

# ABSLOAD STATIC LIBRARIES
ABSLOAD_STAT_LIBS := ncurses utils
ABSLOAD_STAT_LIBS := $(addprefix -l, $(ABSLOAD_STAT_LIBS))

# ABSLOAD SOURCES WITHOUT DIRECTORIES's PREFIXES
ABSLOAD_SRCS_NOTDIR := $(notdir $(wildcard $(ABSLOAD_SRC_DIR)/*.c))

# ABSLOAD OBJECTS
ABSLOAD_OBJS := $(patsubst %.c, $(ABSLOAD_OBJ_DIR)/%.o, $(ABSLOAD_SRCS_NOTDIR))

# ABSLOAD DEPENDENCIES
ABSLOAD_DEPS := $(patsubst %.c, $(ABSLOAD_DEP_DIR)/%.d, $(ABSLOAD_SRCS_NOTDIR))

init:
	mkdir -p bin $(ABSLOAD_OBJ_DIR)

build:	init $(ABSLOAD_BIN)

clean:
	-$(RM) -fr bin $(ABSLOAD_OBJ_DIR) $(ABSLOAD_DEPS)

$(ABSLOAD_OBJ_DIR)/%.o:	$(ABSLOAD_SRC_DIR)/%.c
	$(CC) -c $< $(CC_FLAGS) $(ABSLOAD_INCLUDES) -MMD -o $@

$(ABSLOAD_BIN):	$(ABSLOAD_OBJS)
	$(CC) $^ $(ABSLOAD_LIB_DIRS) $(ABSLOAD_STAT_LIBS) -o $@

-include $(ABSLOAD_DEPS)

.PHONY:	build clean init