# encoding: UTF-8

ASMCMP_BIN := $(BIN_DIR)/asmcmp

ASMCMP_INC_DIR := $(ASMCMP_DIR)/inc
ASMCMP_SRC_DIR := $(ASMCMP_DIR)/src
ASMCMP_OBJ_DIR := $(ASMCMP_DIR)/obj
ASMCMP_DEP_DIR := $(ASMCMP_DIR)/dep

# ASSEMBLER COMPILER INCLUDES
ASMCMP_INCLUDES := -I $(ASMCMP_INC_DIR)
ASMCMP_INCLUDES += 

# ASSEMBLER COMPILER DEFINITIONS
ASMCMP_DEFINITIONS := 
ASMCMP_DEFINITIONS += 

# ASSEMBLER COMPILER SOURCES WITHOUT DIRECTORIES
ASMCMP_SRCS_NOTDIR := $(notdir $(wildcard $(ASMCMP_SRC_DIR)/*.c))

# ASSEMBLER COMPILER OBJECTS
ASMCMP_OBJS := $(patsubst %.c, $(ASMCMP_OBJ_DIR)/%.o, $(ASMCMP_SRCS_NOTDIR))

# ASSEMBLER COMPILER DEPENDENCIES
ASMCMP_DEPS := $(patsubst %.c, $(ASMCMP_DEP_DIR)/%.d, $(ASMCMP_SRCS_NOTDIR))

$(ASMCMP_OBJ_DIR)/%.o: $(ASMCMP_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(ASMCMP_DEFINITIONS) $(ASMCMP_INCLUDES) -MMD -o $@
	@$(MV) $(patsubst %.o, %.d, $@) $(ASMCMP_DEP_DIR)

-include $(ASMCMP_DEPS)