# encoding: UTF-8

ASMCMP_BIN := $(BIN_DIR)/asmcmp

ASMCMP_INC_DIR := $(ASMCMP_DIR)/inc
ASMCMP_SRC_DIR := $(ASMCMP_DIR)/src
ASMCMP_OBJ_DIR := $(ASMCMP_DIR)/obj
ASMCMP_DEP_DIR := $(ASMCMP_DIR)/obj

# ASSEMBLER COMPILER INCLUDES
ASMCMP_INCLUDES := -I $(ASMCMP_INC_DIR)
ASMCMP_INCLUDES += 

# ASSEMBLER COMPILER DEFINITIONS
ASMCMP_DEFINITIONS := 
ASMCMP_DEFINITIONS += 

# ASSEMBLER COMPILER SOURCES
ASMCMP_SRCS := $(wildcard $(ASMCMP_SRC_DIR)/*.c)
ASMCMP_SRCS_NOTDIR := $(notdir $(ASMCMP_SRCS))

# ASSEMBLER COMPILER OBJECTS
ASMCMP_OBJS := $(patsubst %.c, $(ASMCMP_OBJ_DIR)/%.o, $(ASMCMP_SRCS_NOTDIR))
ASMCMP_OBJS_NOTDIR := $(notdir $(ASMCMP_OBJS))

# ASSEMBLER COMPILER DEPENDENCIES
ASMCMP_DEPS := $(patsubst %.o, $(ASMCMP_DEP_DIR)/%.d, $(ASMCMP_OBJS_NOTDIR))
ASMCMP_DEPS_NOTDIR := $(notdir $(ASMCMP_DEPS))

$(ASMCMP_OBJ_DIR)/%.o: $(ASMCMP_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(ASMCMP_DEFINITIONS) $(ASMCMP_INCLUDES) -MMD -o $@

-include $(ASMCMP_DEPS)