# encoding: UTF-8

PLCMP_BIN := $(BIN_DIR)/plcmp

PLCMP_INC_DIR := $(PLCMP_DIR)/inc
PLCMP_SRC_DIR := $(PLCMP_DIR)/src
PLCMP_OBJ_DIR := $(PLCMP_DIR)/obj
PLCMP_DEP_DIR := $(PLCMP_DIR)/dep

# PL COMPILER INCLUDES
PLCMP_INCLUDES := -I $(PLCMP_INC_DIR)
PLCMP_INCLUDES += 

# PL COMPILER DEFINITIONS
PLCMP_DEFINITIONS := 
PLCMP_DEFINITIONS += 

# PL COMPILER SOURCES
PLCMP_SRCS_NOTDIR := $(notdir $(wildcard $(PLCMP_SRC_DIR)/*.c))

# PL COMPILER OBJECTS
PLCMP_OBJS := $(patsubst %.c, $(PLCMP_OBJ_DIR)/%.o, $(PLCMP_SRCS_NOTDIR))

# PL COMPILER DEPENDENCIES
PLCMP_DEPS := $(patsubst %.c, $(PLCMP_DEP_DIR)/%.d, $(PLCMP_SRCS_NOTDIR))

$(PLCMP_OBJ_DIR)/%.o: $(PLCMP_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(PLCMP_INCLUDES) -MM -MF \
$(addprefix $(PLCMP_DEP_DIR)/, $(patsubst $(PLCMP_OBJ_DIR)/%.o, %.d, $@))
	$(CC) -c $< $(FLAGS) $(PLCMP_INCLUDES) -o $@

-include $(PLCMP_DEPS)