COMMON_INC_DIR := $(COMMON_DIR)/inc
COMMON_SRC_DIR := $(COMMON_DIR)/src
COMMON_OBJ_DIR := $(COMMON_DIR)/obj
COMMON_DEP_DIR := $(COMMON_DIR)/obj

# COMMON INCLUDES
COMMON_INCLUDES := -I $(COMMON_INC_DIR)
COMMON_INCLUDES += 

# COMMON DEFINITIONS
COMMON_DEFINITIONS := 
COMMON_DEFINITIONS += 

# COMMON SOURCES
COMMON_SRCS := $(wildcard $(COMMON_SRC_DIR)/*.c)
COMMON_SRCS_NOTDIR := $(notdir $(COMMON_SRCS))

# COMMON OBJECTS
COMMON_OBJS := $(patsubst %.c, $(COMMON_OBJ_DIR)/%.o, $(COMMON_SRCS_NOTDIR))
COMMON_OBJS_NOTDIR := $(notdir $(COMMON_OBJS))

# COMMON DEPENDENCIES
COMMON_DEPS := $(patsubst %.o, $(COMMON_DEP_DIR)/%.d, $(COMMON_OBJS_NOTDIR))
COMMON_DEPS_NOTDIR := $(notdir $(COMMON_DEPS))

$(COMMON_OBJ_DIR)/%.o: $(COMMON_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(COMMON_INCLUDES) -MMD -o $@

-include $(COMMON_DEPS)