#ifndef PLCMP_MAIN_H
#define PLCMP_MAIN_H

typedef enum plcmp_main_error_code_e {
    PLCMP_MAIN_SUCCESS = 0, PLCMP_MAIN_SUCCESSFUL_TRANSLATION = 0,
    PLCMP_MAIN_WRONG_NUM_CLI_PAR,
    PLCMP_MAIN_WRONG_INPUT_PL1_FILE_PATH,
    PLCMP_MAIN_WRONG_INPUT_PL1_FILE_EXTENSION,
    PLCMP_MAIN_NOT_FOUND_INPUT_PL1_FILE,
    PLCMP_MAIN_ERROR_READING_PL1_FILE,
    PLCMP_MAIN_PROGRAM_BUFFER_OVERFLOW,

} plcmp_main_error_code_t;



#endif /* PLCMP_MAIN_H */